version: '3'

services:
  backend:
    build: ./
    container_name: EZCryptoExchange
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    volumes:
      - ./.env:/usr/src/app/.env