version: '3'

services:
  backend:
    build: ./
    container_name: EZCryptoExchange

    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - GOOGLE_CLIENTID=44185310538-c107ojpnshc57dtkeipcm8nvc7glme5u.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      - APP_PORT=3001
      - GOOGLE_CALLBACK_URL=http://52.78.206.45:3001/api/auth/google/redirect
      - KAKAO_CLIENTID=ea6e7a064dd68c986c9c28153f2e9d4d
      - KAKAO_SECRET=XT15CeDinRRx2M9Ju3h70S1AiDpghKjM
      - KAKAO_CALLBACK_URL=http://dnkftcaem7gao.cloudfront.net/api/auth/kakao/redirect
      - SESSION_SECRET=awefaedfawdagewgwsawedfag
      - KAKAOPAY_SECRET=DEVB707D3F985C29167F2EE70FE078541F72778F
      - WALLET_PRIVATE_KEY=aadc1ad2ae83f6ab618eb3aa02f6d03788a70aa5e6ef9d9b10eef89cadca3896
      - FRONTEND_URL=https://dnkftcaem7gao.cloudfront.net/
      - INFURA_TOKEN=035c5c117cd649d7bdbb5ee61b3cb696
      - MYSQL_PASSWORD=rootroot
      - MYSQL_HOST='ezcryptoexchange.creye0kuc4ct.ap-northeast-2.rds.amazonaws.com'
      - BACKEND_URL=http://52.78.206.45:3001
      - FRONTEND_URL=http://dnkftcaem7gao.cloudfront.net
    ports:
      -"3001:3001"

