version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: EZCryptoExchange
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"