name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          # Add any other environment variables here
        
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ezcryptoexchange:latest

      - name: Delete Old docker container
        run: sudo docker rm -f ezcryptoexchange || true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
            -p 3001:3001 \
            --name ezcryptoexchange \
            --env-file .env \
            ${{ secrets.DOCKERHUB_USERNAME }}/ezcryptoexchange